# Autotelegram Information
site_name: Autotelegram Documentation
site_author: Tobias Thomas
edit_uri: blob/main/docs/

# Repository
repo_name: OSCA-Kampala-Chapter/autotelegram
repo_url: https://github.com/OSCA-Kampala-Chapter/autotelegram

# Configuration
theme:
  name: material
  features:
    #- navigation.tabs
    #- header.autohide #the header is automatically hidden when the user scrolls past a certain threshold, leaving more space for content. Add the following lines to mkdocs.yml:
    - search.suggest
    - search.share
    - search.highlight
  language: en
  
  
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: deep orange

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: deep orange

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: deep orange
  logo: assets/autotelegram-logo.png
  favicon: assets.png
  
    
# defines the order of the markdown
nav:
  - Home: index.md
  - Getting started: get_started.md
  - User Guide:
    - How autotelegram works: "user-guide/how-it-works.md"
    - Making requests: "user-guide/making-requests.md"
    - Working with messages: "user-guide/messages.md"
    - Using Webhooks: "user-guide/webhooks.md"
  - Architecture: architecture.md
  - Reference:
    - application: "reference/application.md"
    - context: "reference/context.md"
    - network: "reference/network.md"
    - parser: "reference/parser.md"
    - api:
      - games api: "reference/api/gamesapi.md"
      - inline api: "reference/api/inlineapi.md"
      - passport api: "reference/api/passportapi.md"
      - payments api: "reference/api/paymentsapi.md"
      - stickers api: "reference/api/stickersapi.md"
      - general api: "reference/api/genapi.md"
    - objects:
      - games: "reference/objects/games/games.md"
      - inline: "reference/objects/inline/inline.md"
      - passport: "reference/objects/passport/passport.md"
      - payments: "reference/objects/payments/payments.md"
      - stickers: "reference/objects/stickers/stickers.md"
      - general:
        - animation: "reference/objects/gen/animation.md"
        - audio: "reference/objects/gen/audio.md"
        - base : "reference/objects/gen/base.md"
        - botcommand: "reference/objects/gen/botcommand.md"
        - callbackquery: "reference/objects/gen/callbackquery.md"
        - chat: "reference/objects/gen/chat.md"
        - chatmember: "reference/objects/gen/chatmember.md"
        - contact: "reference/objects/gen/contact.md"
        - dice: "reference/objects/gen/dice.md"
        - document: "reference/objects/gen/document.md"
        - file: "reference/objects/gen/file.md"
        - forcereply: "reference/objects/gen/forcereply.md"
        - forumtopic: "reference/objects/gen/forumtopic.md"
        - inlinekeyboard: "reference/objects/gen/inlinekeyboard.md"
        - inputfile: "reference/objects/gen/inputfile.md"
        - keyboardbutton: "reference/objects/gen/keyboardbutton.md"
        - location: "reference/objects/gen/location.md"
        - loginurl: "reference/objects/gen/loginurl.md"
        - menubutton: "reference/objects/gen/menubutton.md"
        - message: "reference/objects/gen/message.md"
        - photosize: "reference/objects/gen/photosize.md"
        - poll: "reference/objects/gen/poll.md"
        - proximityalerttriggered: "reference/objects/gen/proximityalerttriggered.md"
        - replykeyboard: "reference/objects/gen/replykeyboard.md"
        - responseparamaters: "reference/objects/gen/responseparameters.md"
        - update: "reference/objects/gen/update.md"
        - user: "reference/objects/gen/user.md"
        - venue: "reference/objects/gen/venue.md"
        - video: "reference/objects/gen/video.md"
        - voice: "reference/objects/gen/voice.md"
        - webapp: "reference/objects/gen/webapp.md"
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md



# These appeal to the footer section of the file and are linked to direct following handles
extra:
  extra_css:
  - stylesheets/extra.css
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/OSCA-Kampala-Chapter/autotelegram
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/oscakampala
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/open-source-community-africa-kampala/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/oscakampala


# These are markdown extensions: `They are used up in highliting of 
# codes and even make the page to look more cute`
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark


  # Plugins: This is a plugin that enables the search engine
  #in the markdown file.
plugins:
- search:
    separator: '[\s\-\.]'
- mkdocstrings:
      custom_templates: templates
      default_handler: python
      handlers:
        python:
          options:
           show_source: false


# Copyright Section: In this section, it's almost the same as adding a copyright tag in the 
#html languange. All waht it does is to add a copyright infomation message within the footer section.
copyright: |
  &copy; 2023 <a href="https://github.com/OSCA-Kampala-Chapter/autotelegram"  target="_blank" rel="noopener">autotelegram</a>