# This workflow runs the autobot test suite againt python 3.10 and the major desktop operating systems.

name: Autobot Tester

on: [pull_request,push]

jobs:
  autobot_ubuntu_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: python -c "import sys; print(sys.version)"
      - run: python "tests/test_inst.py"
